extends: cheminfo-typescript
env:
  browser: true
parserOptions:
  project: tsconfig.base.json
rules:
  camelcase: 0
  '@typescript-eslint/no-dynamic-delete': 0
  '@typescript-eslint/no-explicit-any': 0
