extends: cheminfo-typescript
env:
  browser: true
parserOptions:
  project: tsconfig.base.json
rules:
  camelcase: 'off'
  '@typescript-eslint/no-dynamic-delete': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
